### ISSUE TITLE
Review RC [doc]: environment instructions for dev

### ISSUE THREAD

**Issue by rcaneill** [USEPA/harmonize-wq#63]
Hi,
I am starting my in-depth review and will open issues with my questions / comments on the fly.

I believe that the package is missing some instructions for devs, like:
* how to install the dev environment
* how to run the tests

Here is what I did, I guess it is what should be done:

```
# install
pip install -e .
pip install -r requirements_dev.txt

# run the tests
pytest harmonize_wq
```

**Comment by jbousquin** [comment]
Hi @rcaneill - This (pip install from requirements_dev) was added to the docs contributing page on the [pyOpenSci-review](https://github.com/USEPA/harmonize-wq/blob/pyOpenSci-review/contributing.rst) branch. Once that is passing, merged and the docs built does it seem adequate to close this issue?

**Comment by rcaneill** [comment]
It's good to see it somewhere. However, I believe that "explicit is better than implicit", and so providing the exact commands to type should be done, as in https://github.com/USEPA/harmonize-wq/issues/63#issuecomment-2074401601

I can open a PR for that, or let you do it (or if you disagree please tell me why)
