### ISSUE TITLE
Review RC [doc]: link the different example from README to doc / Add link to documentation

### ISSUE THREAD

**Issue by rcaneill** [USEPA/harmonize-wq#68]
According to pyOpenSci a link to the doc should be added to the README file, as well as links to the small vignettes.

**Comment by jbousquin** [comment]
There is a link to the docs on the github pages in the about section of the repo - this seems like it would be higher level and more accessible than on the readme. There is currently a link to the demos (vignettes) in the readme overview section, an additional link to docs has been added there (d117bd63875ad87410b4e42473d203f38b720e5f).
