### ISSUE TITLE
Review RC [doc]: add citation

### ISSUE THREAD

**Issue by rcaneill** [USEPA/harmonize-wq#69]
Description on how to cite should be added, e.g. with a [citation.cff file](https://citation-file-format.github.io/)
Github then detects the file and adds a new item
![image](https://github.com/USEPA/harmonize-wq/assets/18579092/2fb2fcb6-0140-4c7c-a4fb-37ba17d06d97)

**Comment by jbousquin** [comment]
Great suggestion for after JOSS publication
